[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools>=65.5.0', 'wheel']

[project]
authors = [
    {name = 'Stefano Ubbiali', email = 'subbiali@phys.ethz.ch'},
]
dependencies = [
    'hpc_scripts_common @ git+https://github.com/stubbiali/hpc-scripts.git@namespaces#subdirectory=hpc-scripts-common'
]
description = 'Scripts for LUMI @ CSC'
name = 'hpc_scripts_lumi'
version = '0.0'

[project.scripts]
make_build_hdf5 = 'hpc_scripts.lumi.make_build_hdf5:main'
make_build_nco = 'hpc_scripts.lumi.make_build_nco:main'
make_build_netcdf = 'hpc_scripts.lumi.make_build_netcdf:main'
make_prepare_cloudsc = 'hpc_scripts.lumi.make_prepare_cloudsc:main'
make_prepare_cloudsc2 = 'hpc_scripts.lumi.make_prepare_cloudsc2:main'
make_prepare_ecrad = 'hpc_scripts.lumi.make_prepare_ecrad:main'
make_prepare_ecrad_versions = 'hpc_scripts.lumi.make_prepare_ecrad_versions:main'
make_prepare_mpi = 'hpc_scripts.lumi.make_prepare_mpi:main'
make_prepare_pmap = 'hpc_scripts.lumi.make_prepare_pmap:main'
make_select_gpu = 'hpc_scripts.lumi.make_select_gpu:main'
pysalloc = 'hpc_scripts.lumi.salloc:main'
sbatch_ecrad_versions = 'hpc_scripts.lumi.sbatch_ecrad_porting:main'
sbatch_pmap = 'hpc_scripts.lumi.sbatch_pmap:main'

[tool.setuptools.packages.find]
where = ["src/"]
include = ["hpc_scripts.lumi"]
namespaces = true
